services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${NX_POSTGRES_USER}
      - POSTGRES_PASSWORD=${NX_POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5555:5432'
volumes:
  postgres:
